### ISSUE TITLE
Использовать метод equals реализованный у объекта 

### ISSUE THREAD

**Issue by Bratchvv** [aleksan7772/Laba18#3]
https://github.com/aleksan7772/Laba18/blob/7d5f20b0c58c461306d2f9baf35d2d16b5fb9d3a/src/com/brain/lab18/exception/MoneyTransactionUtil.java#L23
Использование `Objects.equals`  здесь неуместно. Нужно заменить на штатный equals

**Comment by aleksan7772** [comment]
тоже исправил
